url: https://jaim-gem.github.io
baseurl: 

# Site settings
title: World of Tech
email: jaimie.greasley@gmail.com
description: " World of Tech (WoT) is an educational website created by TTLAB and launched with NIHERST's Sci-TechKnoFest 2.0 in March 2022. WoT aims to educate people of all ages on Artificial Intelligence (A.I.), Internet of Things (IoT) and Quantum Computing (QC)."
site-image: /img/siteimage.png 

# Team names, titles and social links
people:
- name: Kaveer Bachoo
  pic: 1
  position: Data Scientist
  social:
    - title: facebook
      url: https://www.facebook.com/kaveer.bachoo
    - title: instagram 
      url: https://www.instagram.com/kaveerbachoo/
    - title: inbox
      url: mailto:kaveer_bachoo@hotmail.com

- name: Jaimie Greasley
  pic: 2
  position: Research Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jaimiegreasley/
    - title: github
      url: https://github.com/Jaim-gem
    - title: globe 
      url: https://www.jgphysics.com
    - title: inbox
      url: mailto:jaimie.greasley@gmail.com

- name: Jodhan Medina 
  pic: 3
  position: Data Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jodhan-medina-430624225/
    - title: inbox
      url: malito:jodhanmedina@gmail.com
      
- name: Mindy Mohammed  
  pic: 4
  position: Data Scientist
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/fazeeia-mohammed-528a42b9/
    - title: inbox
      url: mailto:mindy.moh@gmail.com
      

  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: facebook
    url: https://www.facebook.com/info.lab.tt/
  - title: twitter
    url: https://twitter.com/ttlabgroup
  - title: globe 
    url: https://lab.tt/

# Postal address (add as many lines as necessary)
address:
  - line: Trinidad and Tobago 

# Build settings
markdown: kramdown
permalink: pretty
