url: https://jaim-gem.github.io
baseurl: /front-matter/

# Site settings
title: Welcome to World of Tech
email: jaimie.greasley@gmail.com
description: " World of Tech (WoT) is an educational website created by TTLAB and launched with NIHERST's Sci-TechKnoFest 2.0 in March 2022. WoT aims to educate people of all ages on Artificial Intelligence (A.I.), Internet of Things (IoT) and Quantum Computing (QC)."


# Team names, titles and social links
people:
- name: Kaveer Bachoo
  pic: 1
  position: Data Scientist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Jaimie Greasley
  pic: 2
  position: Research Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jaimiegreasley/
    - title: github
      url: https://github.com/Jaim-gem
    - title: website 
      url: https://www.jgphysics.com

- name: Jodhan Medina 
  pic: 3
  position: Data Scientist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
      
- name: Fazeeia Mindy Mohammed  
  pic: 4
  position: Data Scientist 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: facebook
    url: https://www.facebook.com/info.lab.tt/
  - title: twitter
    url: https://twitter.com/ttlabgroup
  - title: website 
    url: https://lab.tt/

# Postal address (add as many lines as necessary)
address:
  - line: Trinidad and Tobago 

# Build settings
markdown: kramdown
permalink: pretty
