# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


url: https://jaim-gem.github.io
baseurl: 

# Site settings
title: World of Tech
email: jaimie.greasley@gmail.com
description: " World of Tech (WoT) is an educational website created by TTLAB and launched with NIHERST's Sci-TechKnoFest 2.0 in March 2022. WoT aims to educate people of all ages on Artificial Intelligence (A.I.), Internet of Things (IoT) and Quantum Computing (QC)."

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Team names, titles and social links
people:
- name: Kaveer Bachoo
  pic: 1
  position: Data Scientist
  social:
    - title: facebook
      url: https://www.facebook.com/kaveer.bachoo
    - title: instagram 
      url: https://www.instagram.com/kaveerbachoo/
    - title: inbox
      url: mailto:kaveer_bachoo@hotmail.com

- name: Jaimie Greasley
  pic: 2
  position: Research Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jaimiegreasley/
    - title: github
      url: https://github.com/Jaim-gem
    - title: globe 
      url: https://www.jgphysics.com
    - title: inbox
      url: mailto:jaimie.greasley@gmail.com

- name: Jodhan Medina 
  pic: 3
  position: Data Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jodhan-medina-430624225/
    - title: inbox
      url: malito:jodhanmedina@gmail.com
      
- name: Mindy Mohammed  
  pic: 4
  position: Data Scientist
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/fazeeia-mohammed-528a42b9/
    - title: inbox
      url: mailto:mindy.moh@gmail.com
      

  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: facebook
    url: https://www.facebook.com/info.lab.tt/
  - title: twitter
    url: https://twitter.com/ttlabgroup
  - title: globe 
    url: https://lab.tt/

# Postal address (add as many lines as necessary)
address:
  - line: Trinidad and Tobago 

# Build settings
markdown: kramdown
permalink: pretty

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
